# Generated by Django 3.1.5 on 2021-01-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruit',
            new_name='Application',
        ),
    ]
