# Generated by Django 3.1.5 on 2021-01-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20210120_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='default@site.com', max_length=254),
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(to='recruit.Question')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='recruit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruit.recruit'),
        ),
    ]
