# Generated by Django 3.1.5 on 2021-01-20 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20210120_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.recruit'),
        ),
    ]
