# Generated by Django 3.1.5 on 2021-01-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20210120_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.question')),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='answers',
            field=models.ManyToManyField(to='recruit.Answer'),
        ),
    ]
